install.packages("pryr")
install.packages("plyr")
install.packages("ISLR")
require(pryr)
require(ISLR)
require(boot)
library(data.table)
library(plyr)
library(pryr)
Student <- read.table(file.choose("Assignment 6 Dataset.txt"), header = TRUE, sep = ",")
Student
StudentAverage <- ddply(Student, "Sex", transform, Grade.Average = mean(Grade))
write.table(StudentAverage, "Sorted_Average", sep = ",")
newStudent <- subset(Student, grepl("[i]", Student$Name))
write.table(newStudent, "DataSubset", sep = ",")
